name: esp-idf-ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:v5.2.2
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Build (esp32s3)
        run: |
          source /opt/esp/idf/export.sh
          idf.py --version
          idf.py set-target esp32s3
          idf.py build
